# Generated by Django 3.2.9 on 2024-06-06 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Analyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='none', max_length=150)),
                ('Phone_Number', models.CharField(default='none', max_length=150)),
                ('Payment_Period', models.CharField(default='none', max_length=150)),
                ('Dates', models.CharField(default='none', max_length=150)),
                ('First_Message_Date', models.CharField(default='none', max_length=150)),
                ('Second_Message_Date', models.CharField(default='none', max_length=150)),
                ('Amount', models.CharField(default='none', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='none', max_length=150)),
                ('Phone_Number', models.CharField(default='none', max_length=150)),
                ('Payment_Period', models.CharField(default='none', max_length=150)),
                ('Dates', models.CharField(default='none', max_length=150)),
                ('First_Message_Date', models.CharField(default='none', max_length=150)),
                ('Second_Message_Date', models.CharField(default='none', max_length=150)),
                ('Amount', models.CharField(default='none', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
