# Generated by Django 3.2.9 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Amount',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='Dates',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='First_Message_Date',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='Payment_Period',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone_Number',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='Second_Message_Date',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Amount',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Dates',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='First_Message_Date',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Name',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Payment_Period',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Phone_Number',
            field=models.TextField(default='none', max_length=150),
        ),
        migrations.AlterField(
            model_name='client_analyzer',
            name='Second_Message_Date',
            field=models.TextField(default='none', max_length=150),
        ),
    ]
